version: "3.4"

services:
  redis:
    container_name: redis-db
    image: "redis:latest"
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    volumes:
      - ./data/redisdata:/usr/local/etc/redis/redis.conf
    networks:
      - backend
   
  postgresql: 
    container_name: postgres-db
    image: "postgres"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khong123
      POSTGRES_DB: postgres_bai1
    networks:
      - backend  
    volumes:
     - ./data/pgdata:/var/lib/postgresql/data

  go:
    container_name: go
    build: 
      context: .
      dockerfile: dockerfile
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./.env:/.env
    restart: always
    depends_on:
      - "redis"
      - "postgresql"
    # extra_hosts:
    #   - "postgres.demo.com:192.168.1.83"
networks:
  backend:
    driver: bridge

# volumes:
#   dataredis: 
#     driver: local
#   pgdata:
#     driver: local

